### ISSUE TITLE
Strange build issues after add and use Fabulous.SimpleElements 

### ISSUE THREAD

**Issue by albertwoo** [Zaid-Ajaj/fabulous-simple-elements#14]
Hi, I am trying to use this library in Visual studio 2019 and got a lot of errors:
1. I create project from **dotnet new fabulous-xf-app -n SqueakyApp**
2. Build and run successful
3. Use **dotnet add package Fabulous.SimpleElements** for the project SqueakyApp
4. Use its function like 
```fsharp
    let view (model: Model) dispatch =
        View.ContentPage(
          content = View.StackLayout(padding = 20.0, verticalOptions = LayoutOptions.Center,
            children = [ 
                Button.button [ Button.Text "123" ]
                ....
```
5. Build the solution, I got error "**error XA2002: Can not resolve reference: `Fabulous.SimpleElements`**" 
6. Use nuget management in visual studio 2019 to add Fabulous.SimpleElements to the SqueakyApp.Android will also get error and cannot be done.
7. I directly add Fabulous.SimpleElements to SqueakyApp3.Android`s packages.config and try to rebuild and still get error
8. I cloned the repo and tried with sample SimpleFabimals, I tried remove the project directly dependence for project SimpleFabimals and added nuget package "Fabulous.SimpleElements" and build the solution, get error "error : AndroidManifest file does not exist"

I cannot figure out how to solve this. Please help.

**Comment by Blener** [comment]
Hello @albertwoo 
Could you please try adding these two lines in the Android packages.config:
```
<package id="System.Numerics.Vectors" version="4.5.0" />
<package id="Xamarin.Android.Arch.Lifecycle.LiveData" version="1.1.1.1" />
```

After that you should be able to add Fabulous.SimpleElements in the android project and get rid of XA2002 error.

The package 'Xamarin.Android.Support.Loader 28.0.0.1'is constrained to 'Xamarin.Android.Arch.Lifecycle.LiveData (= 1.1.1.1)' and 'Xamarin.Essentials 1.1.0' is constrained to 'System.Numerics.Vectors (>= 4.5.0)'. That's why the dependency couldn't be resolved.

I was able to run SimpleFabimals using Visual Studio 2019 after this.

**Comment by albertwoo** [comment]
Thanks for your help. It did not work out for me.
But I just created a csharp project for android as a work around, because it is better for manage nuget packages.
I will close this issue because it is mainly the Visual studio issue for not supporting old fsproj for xamarin android well.
